### PR TITLE
NuGet package and Continous Integration with AppVeyor

### PR DESCRIPTION
**Pull request by ivanz**
Hey,

Here is what I have done:

* Upgraded to MSpec 0.9.3 (0.7.0 was too old to run in AppVeyor builds)
* Made a couple of fixes to project references and build order, which were causing issues in CI
* Added Continuous Integration: build, test, version patching, nuget and vsix creation (look at `appveyor.yml`)
* .nupkg and .vsix artefact generation (see screenshot)
* Deployed a pre-release package here: https://www.nuget.org/packages/Machine.Specifications.Runner.VisualStudio/

Completes #23 and #17 .

With this set-up I can release the NuGet with a single click from my AppVeyor account and my NuGet account, which leads me to what's outstanding:

1. What shall we do about account ownership? (AppVeyor and NuGet)
2. I need admin right and not just collaborator right on GitHub for the repository in order to set-up build hooks and pull request hooks. 

image

image

### CODE REVIEW

**Comment by JonathanWilkins** [comment]
If you could add me as an owner that would be great, Nuget account is JonathanTWilkins.
Not to sure if I can give you admin access to repo as it is under my personal account not under organisation. If I'm missing something let me know.

**Comment by ivanz** [comment]
# NuGet package

I have added you as an owner of the NuGet package - I think you need to accept it in the email which they will send to you.

# Build triggers / GitHub permissions

You are right - I can't find a way to make a collaborator an administrator on one of my own repos either. AppVeyor has very neat tight integration with GitHub including automatic building, enforcing successful builds before merging pull requests and automatically creating GitHub releases.

Are you potentially open to creating a GitHub organization for this project (happy to set it up myself and add you as an admin), so that permissions can be managed better and integration management can be shared? This means that the repo will be hosted under e.g. github.com/machine.visualstudio/

Another option is to check with the MSpec guys if they will be willing to take it under the mspec organization here: https://github.com/machine and give admin permissions for the repo. I am happy to check with them if you want?

The latter will probably be better in terms of centralizing mspec and surrounding effort. Thoughts?

# VSIX

Does the Visual Studio gallery support adding a collaborator out of interest?

**Comment by JonathanWilkins** [comment]
Got the invite to the nuget package.
Putting it under the mspec organization sounds like a good idea. I have created an organization and invited you. We can probably keep it here for the time being and then try and move it into the mspec organization.
Regarding the VSIX you can't do much with that can't seem to add contributors or even transfer ownership, I had to create a whole new package when I took over ownership.

**Comment by ivanz** [comment]
@JonathanWilkins  Thanks. I've accepted the invite. Can you give me admin rights, so that I can connect Appveyour into the organization?

**Pull request merged**
